name: Daily Update
on:
  push:
  # schedule:
  #   - cron: "0 0 * * *"
env:
  USERNAME: brettcannon
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2
      - name: Get Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Update README.md
        run: python --username ${{ env.USERNAME }} --token ${{ secrets.GITHUB_TOKEN }} > README.md
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md
          file_pattern: README.md
